import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
const spartanBold = localFont({
	src: './fonts/LeagueSpartan-Bold.ttf',
	variable: '--font-geist-sans',
	weight: '700'
})
const spartanMedium = localFont({
	src: './fonts/LeagueSpartan-Medium.ttf',
	variable: '--font-geist-sans',
	weight: '600'
})
const spartanSemiBold = localFont({
	src: './fonts/LeagueSpartan-SemiBold.ttf',
	variable: '--font-geist-sans',
	weight: '500'
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${spartanBold.variable} ${spartanMedium.variable} ${spartanSemiBold.variable} antialiased`}>
				{children}
			</body>
		</html>
	)
}
